Us 7.5
WildCodeSchool/2022-09-php-remote-p2-super-quizz pull request #13
Opened 2022-11-13 11:58 UTC by Florent-V

fonction upload des photos avec actualisation du update pour back office ok

2022-11-14 10:27 UTC, Maria-dsa approved these changes
OK

2022-11-14 10:37 UTC, Nicolas-Montard approved these changes

2022-11-14 10:37 UTC, alimag973 approved these changes
ok

2022-11-15 15:17 UTC, jfm-wcs requested changes

2022-11-15 15:17 UTC, jfm-wcs commented on src/Controller/QuestionController.php
> +        );
convertir en `public const FILE_UPLOAD_ERRORS` pour y faire référence partout où c'est nécessaire

2022-11-15 15:17 UTC, jfm-wcs commented on src/Controller/QuestionController.php
> +            if ($_FILES['picture']['error'] != 4) {
FAIRE REF. À `FILE_UPLOAD_ERRORS`

2022-11-15 15:17 UTC, jfm-wcs commented on src/View/Admin/_form.html.twig
> +			</div> #}
dead code ;)

2022-11-15 20:01 UTC, Florent-V commented on src/Controller/QuestionController.php
> +        );
corrigé

2022-11-15 20:01 UTC, Florent-V commented on src/Controller/QuestionController.php
> +            if ($_FILES['picture']['error'] != 4) {
corrigé

2022-11-15 20:01 UTC, Florent-V commented on src/View/Admin/_form.html.twig
> +			</div> #}
supprimé

2022-11-15 20:02 UTC, Florent-V commented
Les changements ont été faits.

2022-11-16 08:53 UTC, jfm-wcs approved these changes

2022-11-16 08:53 UTC, merged