us 7.3
WildCodeSchool/2022-09-php-remote-p2-super-quizz pull request #6
Opened 2022-10-31 09:18 UTC by Nicolas-Montard

2022-10-31 13:36 UTC, Florent-V approved these changes
cela me paraît ! Reste plus qu'à croiser les doigts pour qu'il n'y ait pas ou peu de conflits !

2022-11-01 09:03 UTC, Maria-dsa approved these changes
Ca me parait bon. 
Juste dans le AnswerManager, je me pose la question de l'utilisation de static:: plutôt que self:: en ligne 18.

2022-11-02 15:34 UTC, jfm-wcs requested changes
quelques petites choses à modifier à mon sens mais tout est ok dans l'ensemble 👍

2022-11-02 15:34 UTC, jfm-wcs commented on src/Controller/QuestionController.php
> +                echo 'le dernier index est ' . $lastId;
je pense que tu peux retirer cette ligne qui doit dater d'un debug 😉

2022-11-02 15:34 UTC, jfm-wcs commented on src/View/Admin/add.html.twig
> +    {{ dump(errors) }}
je pense que sans les dump c'est mieux 😉

2022-11-02 15:34 UTC, jfm-wcs commented on src/View/Admin/display.html.twig
> +        {{ dump(question) }}
idem, il vaut mieux retirer les dump avant de commit plutôt que de se dire "je les retirerai plus tard"

2022-11-02 15:34 UTC, jfm-wcs commented on src/View/Admin/display.html.twig
> +            <button><a href="/items/edit?id={{ question.id }}">Edit</a></button>
ce lien mène vers la route `/item/edit` ? c'est étrange 🧐

2022-11-02 16:31 UTC, Florent-V commented
Correction effectuée

2022-11-03 06:07 UTC, jfm-wcs reviewed
du coup, 2 petits conflits sont apparus suite au merge de la PR précédente.

2022-11-03 07:27 UTC, Florent-V commented
Conflits résolus !

2022-11-03 09:58 UTC, merged