Us 8
WildCodeSchool/2022-09-php-remote-p2-super-quizz pull request #7
Opened 2022-10-31 13:30 UTC by Florent-V

J'ai créé une page admin Sign Up où l'on peut créer son mot de passe. Enregistré crypté en BDD of course ;-)
J'ai créé une page admin Sign In où l'on peut s'identifier et où grâce aux sessions, on pourra accéder aux pages de backoffice.
J'attends d'abord que soit merger la fin de CRUD que Nicolas et moi avons fait pour appliquer ce principe de session à toutes les pages.

2022-11-02 14:58 UTC, alimag973 approved these changes

2022-11-02 14:59 UTC, Nicolas-Montard approved these changes

2022-11-02 14:59 UTC, Maria-dsa approved these changes

2022-11-03 06:15 UTC, jfm-wcs requested changes
quelques petites modifications, rien de très lourd.
Je vous conseille d'attendre l'atelier de cet après-midi pour finaliser cette PR, vous allez sûrement avoir plein d'idées d'amélioration côté parcours UX lors du login/inscription notamment (pour gérer ce truc bizarre avec les classes css dans le controlleur 🫣😅)

2022-11-03 06:15 UTC, jeanfrancois-morin commented on src/Controller/AdminController.php
> +                $display = "d-block";
c'est étonnant de voir un nom de classe css dans le contrôleur. Sa place serait plutôt dans le fichier twig. Au pire tu peux passer un booléen et gérer l'affichage dans le template, qu'en penses-tu ?

2022-11-03 06:15 UTC, jeanfrancois-morin commented on src/Controller/AdminController.php
> +                $display = "d-block";
idem concernant le nom d'une classe css 😉

2022-11-03 06:15 UTC, jeanfrancois-morin commented on src/Model/AdminManager.php
> +        $statement->bindValue('password', hash('sha256', $loginInfos['password']), \PDO::PARAM_STR);
ce serait plutôt la fonction `password_hash`à utiliser. Vous avez tout un atelier demain à ce sujet 😉, tu pourras largement t'en inspirer

2022-11-03 06:15 UTC, jfm-wcs commented on src/View/register_layout.html.twig
> +  font-size: 36px;
oh dommage, tu faisais hyper attention jusqu'ici d'utiliser des unités proportionnelles (.rem). Si tu peux modifier en passant c'est top 😉

2022-11-03 06:15 UTC, jfm-wcs commented on src/View/register_layout.html.twig
> +<body>
et je réalise ici que le css est écrit dans la balise `<style>`, étonnant, pourquoi ne pas l'avoir mis dans un fichier css avec tout le monde ? 🧐

2022-11-03 06:35 UTC, Florent-V commented on src/Controller/AdminController.php
> +                $display = "d-block";
C'est la 1er méthode qui m'est venu quand je voulais gérer l'affichage du message. Je vais voir pour faire ça autrement.

2022-11-03 06:36 UTC, Florent-V commented on src/Model/AdminManager.php
> +        $statement->bindValue('password', hash('sha256', $loginInfos['password']), \PDO::PARAM_STR);
OK je verrai ça ! 😉

2022-11-03 06:42 UTC, Florent-V commented on src/View/register_layout.html.twig
> +  font-size: 36px;
J'ai repris une partie d'une ancienne feuille de style pour gagner du temps et comme ça marchait bien j'ai pas pensé à modifier... Je vais corriger

2022-11-03 06:48 UTC, Florent-V commented on src/View/register_layout.html.twig
> +<body>
Je me souviens que j'avais eu une bonne raison de le faire. Je ne me souviens malheureusement plus de la raison. Mais je me souviens de m'être dit que je le remettrai à sa place. Je suis au regret de constater que j'ai du oublier ! 😂

2022-11-03 09:04 UTC, Florent-V commented on src/Controller/AdminController.php
> +                $display = "d-block";
Pour la fonction signIn de toute façon c'était amené à disparaître. J'avais besoin que la PR de l'US 7.3 soit validé pour finir le parcours utilisateur. Donc pour avancer j'ai juste mis cette phrase pour tester que l'identification par mot de passe fonctionnait bien. Après identification l'utilisateur sera redirigé.
Pour l'autre j'ai corrigé dans twig. Je referai une PR quand on aura fait le cours.

2022-11-06 18:46 UTC, Florent-V commented
J'ai fait des modifications en utilisant le cours de la semaine dernière.
En local phpmd me bloque à cause des exit présents. Pourtant j'ai fait comme le modèle du WorkShop.
J'ai donc outrepassé la vérification après avoir réglé tous les problèmes sauf celui là.

2022-11-08 13:11 UTC, jfm-wcs approved these changes

2022-11-08 13:12 UTC, merged